#! /usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup"

require "green_log/logger"
require "green_log/json_writer"
require "green_log/simple_writer"
require "pry"

case ARGV.first
when "json"
  writer_class = GreenLog::JsonWriter
when "simple", nil
  writer_class = GreenLog::SimpleWriter
else
  raise ArgumentError, "bad format: #{ARGV.first}"
end

logger = GreenLog::Logger.new(writer_class.new(STDOUT))
logger.pry
