#! /usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup"

require "green_log/logger"
require "green_log/json_writer"
require "green_log/simple_writer"
require "pry"

include GreenLog

writer_class = case ARGV.first
when "json"
  JsonWriter
when "simple", nil
  SimpleWriter
else
  raise ArgumentError, "bad format: #{ARGV.first}"
end

logger = Logger.new(writer_class.new(STDOUT))
logger.pry
